version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    branches:
      only:
        - devel
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-firebase
          command: 'npm install firebase-tools'
      - run:
          name: install-dependencies
          command: 'npm install'
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: 'npm run build'
      - run: 
          name: deploy
          command: 'npm run deploy'
