version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    branches:
      only:
        - devel
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-yarn
          command: 'sudo npm install --global yarn'
      - run:
          name: install-firebase
          command: 'sudo npm install -g firebase-tools'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: 'yarn install'
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: 'yarn build'
      - run: 
          name: deploy
          command: 'firebase deploy --token=$FIREBASE_TOKEN --non-interactive'